# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94573321ce23ac3c323da393fadb1e90d1cac444a7ccb31b34716eebd56a374ad0f57a7bce6f6d7b9fd5629ee96f825e5d3064e8a40c00638973d06e2f64e946

test:
  secret_key_base: 6305214da9ee4554bb2fd36a7e5ab6903d1d08326a2f59cdd293b4c1cafc4c1e1fc53c607d8d589a597e455caedce60c2bd828c8e276df5d2704deced6801f88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
